[package]
name = "rustwasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agdb = "0.8.2"
bevy = "0.14.2"
wasm-bindgen = "0.2.93"
